import os
AZURE_OPENAI_API_KEY = os.getenv("AZURE_OPENAI_API_KEY")
AZURE_OPENAI_ENDPOINT = os.getenv("AZURE_OPENAI_ENDPOINT")
AZURE_OPENAI_DEPLOYMENT = "gpt-4o"
AZURE_OPENAI_API_VERSION = "2024-10-21"
TAVILY_API_KEY = os.getenv("TAVILY_API_KEY")
PROJECT_PATH = "../../projects/esp-landing/"